apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.tekton.dev/v1alpha1",
          "kind": "TektonAddon",
          "metadata": {
            "name": "addon"
          },
          "spec": {
            "targetNamespace": "openshift-pipelines"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.5.0
    operators.operatorframework.io/project_layout: unknown
  name: openshift-pipelines-operator-rh.v0.22.0-1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: TektonAddon
      name: tektonaddons.operator.tekton.dev
      version: v1alpha1
    - kind: TektonConfig
      name: tektonconfigs.operator.tekton.dev
      version: v1alpha1
    - kind: TektonDashboard
      name: tektondashboards.operator.tekton.dev
      version: v1alpha1
    - kind: TektonPipeline
      name: tektonpipelines.operator.tekton.dev
      version: v1alpha1
    - kind: TektonTrigger
      name: tektontriggers.operator.tekton.dev
      version: v1alpha1
  description: Openshift Pipelines Operator Rh description. TODO.
  displayName: Openshift Pipelines Operator Rh
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - pods/log
          - limitranges
          verbs:
          - '*'
        - apiGroups:
          - extensions
          - apps
          resources:
          - ingresses
          - ingresses/status
          verbs:
          - delete
          - create
          - patch
          - get
          - list
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          - deployments/finalizers
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
          - delete
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - roles
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - rolebindings
          verbs:
          - get
          - create
          - update
          - delete
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          - customresourcedefinitions/status
          verbs:
          - get
          - create
          - update
          - delete
          - list
          - patch
          - watch
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          - validatingwebhookconfigurations
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - build.knative.dev
          resources:
          - builds
          - buildtemplates
          - clusterbuildtemplates
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - extensions
          resources:
          - deployments
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - extensions
          resources:
          - deployments/finalizers
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - policy
          resources:
          - podsecuritypolicies
          verbs:
          - get
          - create
          - update
          - delete
          - use
        - apiGroups:
          - operator.tekton.dev
          resources:
          - '*'
          - tektonaddons
          verbs:
          - '*'
        - apiGroups:
          - tekton.dev
          - triggers.tekton.dev
          - operator.tekton.dev
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - dashboard.tekton.dev
          resources:
          - '*'
          - tektonaddons
          verbs:
          - '*'
        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - get
          - list
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - console.openshift.io
          resources:
          - consoleyamlsamples
          - consoleclidownloads
          - consolequickstarts
          verbs:
          - '*'
        - apiGroups:
          - autoscaling
          resources:
          - horizontalpodautoscalers
          verbs:
          - '*'
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - '*'
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - '*'
        serviceAccountName: tekton-operator
      deployments:
      - name: tekton-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: tekton-operator
          strategy: {}
          template:
            metadata:
              labels:
                app: tekton-operator
                name: tekton-operator
            spec:
              containers:
              - env:
                - name: IMAGE_TP12_SEAMLESS_DELETE_CONFIG_CRD
                  value: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
                - name: IMAGE_PIPELINES_PROXY
                  value: ko://github.com/tektoncd/operator/cmd/openshift/webhook
                - name: SYSTEM_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: tekton-operator
                image: ko://github.com/tektoncd/operator/cmd/openshift/operator
                imagePullPolicy: Always
                name: tekton-operator
                resources: {}
              serviceAccountName: tekton-operator
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - openshift-pipelines-operator-rh
  links:
  - name: Openshift Pipelines Operator Rh
    url: https://openshift-pipelines-operator-rh.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 0.22.0-1
